debug: false  # ??? ?? ??? ??
management.endpoints.web.exposure.include: "*"  # actuator? ????? ? ??? ? ?? ????

logging:
  # log level ??
  level:
    com.fc.projectboard: debug
    org.springframework.web.servlet: debug
    # JPA? ???? ?? ??? ??? ? ??
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: pepe
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # ???? ?????? ???? ??
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2:
    console:
      enabled: true
  # data.sql? ?? ?????? ?? rule
  sql.init.mode: always

